version: '3.8'

services:
  playwright-tests:
    build: .
    container_name: btl-playwright-tests
    environment:
      - NODE_ENV=test
      - HEADLESS=true
      - BASE_URL=https://training.bt-ms.com/MAIN-STAGE/erp.php
      - MAX_WORKERS=2
      - SCREENSHOT_MODE=only-on-failure
      - VIDEO_MODE=retain-on-failure
    volumes:
      - ./reports:/app/reports
      - ./allure-results:/app/allure-results
      - ./test-results:/app/test-results
    networks:
      - test-network

  allure-server:
    image: frankescobar/allure-docker-service
    container_name: btl-allure-server
    ports:
      - "5050:5050"
    environment:
      CHECK_RESULTS_EVERY_SECONDS: 3
      KEEP_HISTORY: 1
    volumes:
      - ./allure-results:/app/allure-results
      - ./allure-reports:/app/default-reports
    networks:
      - test-network
    depends_on:
      - playwright-tests

  report-server:
    image: nginx:alpine
    container_name: btl-report-server
    ports:
      - "8080:80"
    volumes:
      - ./reports:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - test-network

networks:
  test-network:
    driver: bridge

volumes:
  test-reports:
  allure-data:
