# ⚡ Quick Smoke Tests - Fast Feedback
name: Quick Smoke Tests

on:
  push:
    branches: [main, develop]
    paths:
      - 'src/**'
      - 'tests/**'
      - 'package*.json'
  workflow_dispatch:

env:
  NODE_VERSION: '18'

jobs:
  quick-smoke:
    name: Quick Smoke Tests
    runs-on: ubuntu-latest
    timeout-minutes: 8
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Install Playwright (Chromium only)
        run: npx playwright install chromium --with-deps
        
      - name: Setup environment
        run: |
          cp .env.example .env
          echo "HEADLESS=true" >> .env
          echo "CI=true" >> .env
          echo "MAX_WORKERS=1" >> .env
          
      - name: Run quick smoke tests
        run: npm run test:smoke -- --project=chromium --workers=1
        env:
          BASE_URL: ${{ secrets.STAGING_BASE_URL || 'https://your-app-url.com' }}
          TEST_USER_USERNAME: ${{ secrets.TEST_USER_USERNAME }}
          TEST_USER_PASSWORD: ${{ secrets.TEST_USER_PASSWORD }}
          
      - name: Upload results
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: quick-smoke-results
          path: test-results/
          retention-days: 3
          
      - name: Quick status
        if: always()
        run: |
          if [ "${{ job.status }}" == "success" ]; then
            echo "✅ Quick smoke tests passed! Core functionality working."
          else
            echo "❌ Quick smoke tests failed! Check critical paths."
            echo "::error::Critical functionality issues detected"
          fi

      - name: Check Teams Webhook
        id: check-webhook
        run: |
          if [ -n "${{ secrets.TEAMS_WEBHOOK }}" ]; then
            echo "webhook_available=true" >> $GITHUB_OUTPUT
          else
            echo "webhook_available=false" >> $GITHUB_OUTPUT
            echo "ℹ️ Teams webhook not configured - skipping notification"
          fi

      - name: Send Teams Notification
        if: failure() && steps.check-webhook.outputs.webhook_available == 'true'
        uses: aliencube/microsoft-teams-actions@v0.8.0
        with:
          webhook_uri: ${{ secrets.TEAMS_WEBHOOK }}
          title: "⚡ Quick Smoke Test Failed"
          summary: "❌ Critical functionality issues detected"
          text: |
            **Repository**: ${{ github.repository }}
            **Branch**: ${{ github.ref_name }}
            **Commit**: ${{ github.sha }}
            **Build**: ${{ github.run_number }}
            
            🚨 **Quick smoke tests failed!** This indicates issues with core functionality.
            
            Please check the failing tests immediately.
            
            [🔍 View Workflow Run](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }})
          theme_color: "dc3545"
